### ISSUE TITLE
Renommer le titre du projet

### ISSUE THREAD

**Issue by FannyLbr** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#1]
Je pense qu'il faudrait renommer le nom du projet car il a plusieurs défauts. Il paraît long et les conventions de nommage ne sont pas harmonisées (Berlioz = nom, Nanci = prénom). 
Je propose donc : "Projet_Correspondance_Berlioz". Qu'en pensez-vous ?

**Comment by Lienceard** [comment]
C'est possible de renommer le projet. Toutefois, il va falloir mettre à jour le lien entre le dépôt local git et le dépôt distant sur gitHub.
Je pense faire dans un premier temps les commandes `git remote set-url origin new_url` et `git push -u origin main` pour mon premier commit.

**Comment by SjdkC** [comment]
D'accord pour le changement de nom, merci pour ta proposition @FannyLbr.
Entendu @Lienceard, cela me semble bien !

**Comment by FannyLbr** [comment]
Super Lien, cela me semble bien aussi, merci !

**Comment by Lienceard** [comment]
Je vais réaliser cette modification dès que possible.

**Comment by Lienceard** [comment]
J'ai réussi à modifier le nom du dépôt distant sur gitHub du projet.

**Comment by FannyLbr** [comment]
Après relecture des consignes du devoir, je me suis aperçue que le modèle du titre devait être le suivant : TNAH-2021-{PROJET}. Je propose alors le titre suivant : TNAH-2021-Correspondance-Berlioz. Êtes-vous d'accord ?

**Comment by SjdkC** [comment]
D'accord pour moi, merci encore !

**Comment by Lienceard** [comment]
je pensais le renommer de la manière suivante: TNAH-2021-Projet_Correspondance_Berlioz

**Comment by FannyLbr** [comment]
Si tu veux, mais je pense qu'il vaut mieux harmoniser les tirets. Utilisons "-" plutôt que "_".

**Comment by Lienceard** [comment]
ok. je le fais dès que possible

**Comment by SjdkC** [comment]
D'accord pour moi !
