### ISSUE TITLE
Citation de la source des images (conditions d'utilisation Gallica)

### ISSUE THREAD

**Issue by SjdkC** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#11]
Bonsoir,

Après consultation des [conditions d'utilisation des contenus de Gallica](https://gallica.bnf.fr/edit/conditions-dutilisation-des-contenus-de-gallica), il semblerait qu'il n'y a pas de problème à inclure les images des lettres dans notre dépôt. En revanche, les conditions d'utilisation imposent un modèle pour citer la source des documents :

> La réutilisation non commerciale de ces contenus est libre et gratuite dans le respect de la législation en vigueur et notamment du maintien de la mention de source des contenus telle que précisée ci-après : « Source gallica.bnf.fr / Bibliothèque nationale de France » ou « Source gallica.bnf.fr / BnF ».

Lorsque nous téléchargeons le pdf de nos lettres depuis Gallica, deux pages sont inclues avant le document en lui-même : une page comportant le titre du document et la fameuse mention de source, et une deuxième comprenant des informations légales.
Je me demande donc si nous ne devrions pas garder ces deux pages lorsque nous ajoutons les pdf dans nos dossiers respectifs.

Si nous ne voulons pas que ces deux pages apparaissent pour chaque lettre, une autre solution pourrait être d'inscrire la mention de source dans le README, accompagnée d'un renvoi vers les conditions générales de Gallica. Cependant, il me semble peut-être préférable de ne pas toucher au pdf d'origine, par soucis de facilité et de transparence.

Qu'en pensez-vous ?
Merci par avance pour vos réponses !

**Comment by Lienceard** [comment]
Bonsoir Cécile, 

Pour ma part, quand j'ai téléchargé le pdf j'avais les deux feuilles du début en plus des images des feuillets des lettres. Si bien que je pensais directement mettre les pdf dans chacun des dossiers associés à chacune de mes lettres.
J'ai regardé ce que contenait le pdf des lettres que Fanny a mis sur sa branche. Il n'y avait pas les deux pages.
J'ai fait comme Fanny pour les images de mes lettres
Par soucis d'uniformisation des dossiers de nos lettres dans notre dépôt, cela me semble mieux de se baser sur ce qu'a fait Fanny. Cela éviterait aussi à Fanny de supprimer et de remettre les bons PDFs et des manipulations un peu pénible à faire...

**Comment by Lienceard** [comment]
je me suis basée sur ce qu'avait fait Fanny. J'ai supprimé les deux premières  pages du pdf.

Je pense qu'il ne faut pas trop s'inquiéter étant donné que tu as déjà indiqué l'URL de chacune des lettres dans le tableau de gestion et que tu as dit que nous avions utilisé des ressources de Gallica dans le README...
Cela me semble suffisant...

Pour information, voici la méthode assez simple que j'ai utilisée pour enlever les deux feuillets du début.
J'ai utilisé pdftk qui permet de séparer chacune des pages d'un pdf et de supprimer celles qu'on ne souhaite pas garder.
J'ai installé pdftk à partir de la logithèque Ubuntu.
Puis, dans mon terminal, j'ai rentré la commande suivante : pdftk lenomdufichier cat lesnumérosdespagesàgarder output lenomdemondossierdesortie
exemple : pdftk Lettre_d\'Hector_Berlioz_à_Nanci_\[...\]Berlioz_Hector_btv1b530310260.pdf cat 3 4 5 output Lettre2_04-06-1827.pdf

**Comment by SjdkC** [comment]
Le but de l'issue est justement de se mettre d'accord, donc j'attends l'avis de Fanny et la conclusion de l'issue pour l'harmoniser mes images si besoin est ! Mais en tout cas merci pour la méthode pour "nettoyer" le pdf !

**Comment by FannyLbr** [comment]
Bonjour les filles, 

Merci Cécile d'avoir relevé cette précision. C'est vrai que je ne m'étais pas interrogée là-dessus ... J'ai supprimé les deux premières pages de mes pdfs (titre/mention de source et informations légales) car je ne voulais pas les inclure dans eScriptorium. J'ai donc repris ces fichiers sans ces deux pages que j'ai inclus sur github sans trop me poser de question. 

Si vous y voyez un inconvénient, je peux modifier les pdfs présents sur ma branche, il n'y a aucun problème.

Pour ma part, je ne pense pas que cela pose de problème de ne pas mettre ces deux pages, si nous indiquons précisément ces indications dans le README. Nous avons déjà mentionné les sources, nous pourrions ajouter les informations légales en plus si vous le souhaitez.

**Comment by SjdkC** [comment]
D'accord, je vais donc supprimer les deux pages de mon pdf, et rajouter la mention de source plus précise dans le README !

**Comment by FannyLbr** [comment]
D'accord Cécile, et merci à toi pour l'ajout dans le README !

**Comment by Lienceard** [comment]
D'accord Cécile et merci pour l'ajout de la mention dans le README. Désolée de ne pas avoir attendu.
