### ISSUE TITLE
doutes transcription lettre 1

### ISSUE THREAD

**Issue by Lienceard** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#12]
Bonjour,

J'aurais aimé être aidée dans la transcription de ma lettre 1. J'ai des doutes sur la transcription de certains passages.

image 1:

- ligne 14:

J'ai lu "persister dans ma resolution et d'esor du temps qui m'a été". Mais je ne suis pas sûre qu' "esor" soit le bon mot.

![esor du temps](https://user-images.githubusercontent.com/92690835/147766968-8487b80d-fb35-4887-bab7-435836512fd5.jpeg)

image 2:

- ligne 11:

J'ai lu "d'imnactite de, toutes ses commissions sont faites depuis". Mais je ne pense pas qu"imnactite" soit le bon mot. le "de" situé juste après, va peut-être avec le mot précédent ?

![inactide](https://user-images.githubusercontent.com/92690835/147768006-736d7868-9115-4c68-888c-e10eb5116719.jpeg)

-ligne 15:

J'ai lu "Adele m'avoit promis de m'ecrire je". Les "a" et les "o" se ressemblent beaucoup. Si bien que je me demande si c'est "avait" ou "avoit".

![avoit](https://user-images.githubusercontent.com/92690835/147768667-d680e1bb-5e8f-44bb-b278-51a26e66aec1.jpeg)

Si les captures d'écran sont de trop petites tailles et qu'un complément contextuel est nécessaire à la compréhension de ces passages, vous pouvez vous référer aux images en pdf contenues dans le dossier "Lettre1_04-11-1823 sur la branche "Lien". 

Qu'en pensez-vous? 

Je vous remercie d'avance pour votre aide apportée.

**Comment by SjdkC** [comment]
Bonsoir Lien,

1. Je lis plutôt "d'user" !
2. J'aurais tendance à lire "d'inexactitude" (les "x" de Berlioz ne m'ont pas semblé très marqués ; ici, ça pourrait donc correspondre). Cela me semble possible vis à vis du contexte, mais je n'ai pas de certitude.
3. Le "avoit" m'étonnerait un peu au vue de la période, mais c'est vrai que le tracé fait penser à un "o"...

**Comment by FannyLbr** [comment]
Bonjour Lien, 

1. Ok avec Cécile, je lis "d'user" aussi.
2. Ok avec Cécile, je lis "d'inexactitude" aussi.
3. Oui le tracé semble plus proche du "o" que du "a"... As-tu rencontré d'autres cas similaires dans cette lettre ? Si oui, dans ce cas, il faut essayer d'être le plus uniforme possible sur l'ensemble de la lettre, et faire le même choix partout.

**Comment by Lienceard** [comment]
Bonjour, 

je vous remercie de votre aide.
Je pense que les deux premiers mots que vous avez corrigés sont bons.
oui, j'ai bien rencontré plusieurs fois ce problème de "o" qui ressemblait plus qu'à des "a". 
En avez-vous rencontrés vous aussi ? Si oui qu'avez vous choisi de mettre ?

**Comment by FannyLbr** [comment]
Il ne me semble pas avoir douté sur ce type d'élément, car les lettres étaient, pour ma part, assez bien dessinées. Mais si cela peut t'aider dans ton choix, j'ai eu essentiellement (je crois) une conjugaison moderne et non pas ancienne.

**Comment by SjdkC** [comment]
Je suis dans le même cas que Fanny : je n'ai pas souvenir d'avoir eu d'hésitations sur les lettres, qui étaient plutôt bien formées.

**Comment by Lienceard** [comment]
Je vous remercie beaucoup pour vos retours.
Je vais mettre "avoit" et uniformiser ma transcription de la sorte.

**Comment by Lienceard** [comment]
Bonjour Fanny,

La lettre 1 est prête à être relue.

J'ai encore des doutes sur la transcription de certains passages bien que nous ayons fixé les normes de transcription

image 1:

- ligne 6 : je ne sais pas s'il faut transcrire le trait ,situé après le "mais", et lequel caractère d'écriture à utiliser.

![trait](https://user-images.githubusercontent.com/92690835/148414387-1a757f64-6def-4f99-9ccf-18ad2cce38d6.jpeg)

Je te remercie d'avance pour tes corrections apportées.

Bonne relecture!

**Comment by FannyLbr** [comment]
Bonjour @Lienceard,

J'ai fini la relecture de cette lettre. J'ai effectué deux PR (#23 et #24) pour te proproser mes corrections. (Aucune correction effectuée pour la 3e page, tout était bon). 

Je t'ai expliqué mes corrections lors de mon message des PR, je reviens notamment sur ton interrogation avec le trait. Je te laisse te référer à la PR #23 pour voir ma réponse.

**Comment by Lienceard** [comment]
Bonsoir @FannyLbr 

J'approuve tes propositions. 
Encore un grand merci pour tes relectures.
