### ISSUE TITLE
doutes transcription lettre 2

### ISSUE THREAD

**Issue by Lienceard** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#13]
Bonjour

J'aurais aimé être aidée dans la transcription de ma lettre 1. J'ai des doutes sur la transcription de certains passages.

image 1:

- ligne 6:

Je doute de l'orthographe du dernier mot. Je me demande si on lit "gracieux" ou "gracieus". Les "s" et les "x" à la fin des mots se ressemblent beaucoup. Je vais retrouver cette même graphie dans plusieurs mots qui me pose quelques soucis. C'est pourquoi je ne mets que l'exemple d'un cas rencontré. 

![gracieux](https://user-images.githubusercontent.com/92690835/147770590-a986be90-c894-44a2-9ac6-31383f15acca.jpeg)

- ligne 8:

J'ai lu "de le prendre si je veux le tenter, je commence par reflechir". Mais je doute que cela soit "tenter".

![tendre](https://user-images.githubusercontent.com/92690835/147771354-e6450ba7-a851-423e-963a-467fa3d6e2bf.jpeg)

Si les captures d'écran sont de trop petites tailles et qu'un complément contextuel est nécessaire à la compréhension de ces passages, vous pouvez vous référer aux images en pdf contenues dans le dossier "Lettre2_04-06-1827 sur la branche "Lien".

Qu'en pensez-vous?

Je vous remercie d'avance pour votre aide apportée.

**Comment by SjdkC** [comment]
Bonsoir !

1. Je lirai plutôt un "x". Berlioz ratatine ses "x", mais à mon avis ça y correspond quand même !
2. Je lis aussi "tenter", mais sans certitude...

**Comment by FannyLbr** [comment]
Bonjour,

1. Je lis plutôt un "x" aussi.
2. Je lis aussi "tenter", je ne pense pas que cela soit autre chose (cela aurait pu être "tester" mais la troisième lettre ne ressemble en rien à un "s". Je n'ai pensé à aucun autre mot). J'ajoute juste une petite précision (je ne sais pas si c'est un oubli de ta part ou si c'est moi qui lis mal), mais il y a un point-virgule après "de le prendre ;".

**Comment by Lienceard** [comment]
Bonjour,

Je vous remercie pour votre aide.
d'accord pour le "x" à la fin de gracieux.
d'accord pour "tenter"
oui j'ai bien oublié un point virgule...
D'ailleurs, je pense peut-être vous faire prochaine une capture d'écran d'une virgule ou d'un point-virgule car ils sont pas facile à différencier.

**Comment by Lienceard** [comment]
Bonjour Fanny,

La lettre 2 est prête à être relue.
J'ai encore des doutes qui persistent pour la transcription de certains passages.

image 1
- ligne 21 : J'ai un doute pour transcrire une rature, sachant que l'auteur a mis en dessous le "e" du mot "que".

![que](https://user-images.githubusercontent.com/92690835/148420055-2c17fc6a-5857-4574-9dea-6c355cae7130.jpeg)

image 2
-ligne 6 : je rencontre le même problème que celui indiqué pour l'image 1.

![image](https://user-images.githubusercontent.com/92690835/148420611-e046771e-d342-4abe-9422-63539ec6c5e9.png)

Je te remercie d'avance pour tes corrections.

Bonne relecture!

**Comment by FannyLbr** [comment]
Bonsoir @Lienceard,

J'ai fini la relecture de cette lettre. J'ai effectué trois PR (#27, #29 et #30) pour te proproser mes corrections. 

Je t'ai expliqué mes corrections lors de mon message des PR, je reviens également sur tes interrogations formulées ici. Je te laisse te référer aux PR #27 et #29 pour voir mes réponses à leur sujet.

**Comment by Lienceard** [comment]
Bonsoir @FannyLbr 

Je te remercie beaucoup pour tes corrections.
Je les valide.
