### ISSUE TITLE
Intégration continue : relecture des transcriptions

### ISSUE THREAD

**Issue by Lienceard** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#14]
Bonjour à toutes,

Nous sommes sur le point de terminer les premières transcriptions de nos lettres et de formaliser les normes de transcription. Il faudrait peut-être réfléchir, à ce stade de notre projet, à l'intégration continue de nos transcriptions. C'est à dire aux relectures des transcriptions.

Je souhaitais vous proposer l'organisation suivante.

Si je me souviens bien avec Fanny et peut-être Cécile, nous avions rapidement discuté ensemble du système suivant. Fanny relirait mes transcriptions. Cécile relirait celles de Fanny. Je relirais celles de Cécile. Je pense qu'il est bien. Il permet d'éviter à chacune de relire toutes les transcriptions à chaque phase de relecture. On aura discuter des problèmes de transcription et de normalisation dans des issues.

Dans un premier temps, il faudrait peut-être effectuer une première relecture de type "orthographique". Mais elle n'est peut-être pas nécesaire puisqu'à chaque fois qu'on a eu un doute sur l'orthographe d'un mot, on a créé une issue pour recevoir l'aide des autres membres du groupe.

Ensuite, je pensais qu'on laisserait le temps à chacune d'appliquer les normes qui auront été formalisées à ses propres transcriptions.
Des relectures pourraient être faites afin de vérifier l'application de ces normes.
L'auteur des transcriptions et le relecteur auront peut-être à soumettre des propositions de nouvelles normes.
C'est pourquoi cela donnera peut-être à de nouvelles relectures et le cycle se répéterait jusqu'à ce qu'on ait régler l'ensemble des problèmes de normalisation.

Enfin, les relectures seraient une bonne occasion d'utiliser les pull requests afin de laisser aux auteurs des transcriptions le soin de valider les propositions faites par les relecteurs. 

Qu'en pensez-vous ?

**Comment by FannyLbr** [comment]
Bonjour Lien, 

Je suis d'accord pour ta proposition, cela me paraît pratique (Fanny -> Lien, Cécile -> Fanny, Lien -> Cécile).

En revanche, je ne pense pas qu'une relecture "orthographique" (ou plutôt de transcription tu veux dire ?) à proprement parler soit nécessaire, car d'une part, pour éviter de relire plusieurs fois les lettres des autres, il vaut mieux avoir un "produit fini" où les règles de transcriptions seraient déjà appliquées avant de se lancer dans les relectures des lettres des autres. D'autre part, effectivement, nous avons déjà discuté dans les issues des problèmes de déchiffrage rencontrés, il n'est donc pas nécessaire de réaliser une relecture spécifique aux soucis de déchiffrage. Ceci dit, on n'est pas à l'abri de nous être trompée sans s'en rendre compte, il faudra donc rester vigilante quand nous ferons la relecture finale sur ce point.

Je pense donc (mais ce n'est que mons avis), qu'il faudrait finir la transcription de nos lettres respectives avec l'application des normes de transcription avant de nous lancer dans la relecture des lettres des autres. Et comme cela, quand nous nous lancerons dans ces relectures, nous pourrons prendre en compte tous les aspects (vigilance sur le déchiffrage, mais aussi sur les règles de transcriptions appliquées). Nous pourrons ensuite réaliser des PR pour proposer des corrections (comme tu l'as proposé). 

Qu'en pensez-vous ?

**Comment by SjdkC** [comment]
Bonjour,

Tout à fait d'accord pour que la relecture soit effectuée par une personne. 

Je suis d'accord avec la proposition de Fanny concernant l'organisation des relectures : à mon avis, il vaut mieux attendre que les normes soient réellement fixées avant de donner notre travail à relire aux autres. Cela nous fera gagner du temps et sera sans doute plus efficace.

**Comment by Lienceard** [comment]
Très bien. 
Je pense qu'on peut adopter ce type d' organisation pour les relectures. Nous les feront après avoir appliquer les normes à nos transcriptions respectives. 
Pensez-vous qu'on peut fermer l'issue?

**Comment by FannyLbr** [comment]
Comme tout le monde est ok sur l'organisation, oui nous pouvons fermer l'issue.
