### ISSUE TITLE
Lettre5_05-02-1942 : doutes sur la transcription

### ISSUE THREAD

**Issue by SjdkC** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#15]
Bonjour à toutes,

Je sollicite votre aide concernant quelques doutes que j'ai vis-à-vis de la transcription de la lettre 5. J'ai joint des images, mais n'hésitez pas à vous reporter à la [version Gallica](https://gallica.bnf.fr/ark:/12148/btv1b53030980v?rk=42918;4) ou aux transcriptions sur ma branche.

1. Image 1, ligne 2 (et oui, déjà !)
![Capture d’écran du 2021-12-30 23-58-51](https://user-images.githubusercontent.com/92724884/147793186-8537d3bc-6c97-4c6f-b4e1-51d6b16f1b51.png)
J'ai un doute sur les deux derniers mots : `petit-opéra` ou `petite opéra`. Je penche plutôt pour la première hypothèse, mais dites moi ce que vous en pensez.

2. Image 1, ligne 5
![image](https://user-images.githubusercontent.com/92724884/147793264-1fd753e3-218c-4756-a66f-0882535ce5ae.png)
`pour les modistes` ou `pour les modestes` ? Là aussi, je penche plutôt pour la première hypothèse, puisque Berlioz parle de marchandes de modes un peu plus haut...

3. Image 1, ligne 22
![image](https://user-images.githubusercontent.com/92724884/147793410-26b31874-55dd-474c-b127-1b8d8264c9f3.png)
Mon doute porte sur les signes qui suivent `C'est un enfer !`. Pour le contexte, il s'agit d'une citation. J'ai donc tendance à lire `"-`. Cependant la citation ne s'ouvre pas avec des guillemets, ce qui me fait douter de mon interprétation. 

4. Image 2, ligne 5
![image](https://user-images.githubusercontent.com/92724884/147793547-e32e9a61-1c71-4af5-a7df-1b040487ccb5.png)
Le mot du milieu me pose problème. Je lis `l'ours`, mais cela n'a pas beaucoup de sens.

5. Image 3, ligne 32 (première ligne verticale)
![image](https://user-images.githubusercontent.com/92724884/147793651-d21bb441-4664-45cf-b0c1-906933082a5a.png)
Ma question porte ici sur le premier mot. Je lis `scribe` mais, là encore, cela ne semble pas coller au contexte.

Je vous remercie par avance pour vos retours !

**Comment by FannyLbr** [comment]
Bonjour Cécile,

1. Je penche aussi pour la première hypothèse puisque "opéra" est masculin, donc "petit-opéra". 

2. À première vue, j'aurai dit un "e", mais effectivement, comme il parle de marchandes de modes un peu plus haut, le mot "modistes" semble être le bon choix. 

3. Effectivement, je suis allée consultée l'intégralité de la lettre, et je comprends comme toi, c'est bien une citation qui commence sans guillemets. Je pense que cela est un oubli de la part de H. Berlioz, car pour moi, la citation finit bien comme ceci : ' !" — '. Je pense que tu peux laisser la chose telle quelle, puisque nous faisons le choix d'être au plus proche du manuscrit, et donc ne restitue pas le début du guillemet.

4. Je lis bien "l'ours" aussi... Peut-être utilise-t-il ce mot pour nommer implicitement quelqu'un ? 

5. C'est bien "Scribe". Il s'agit d'Eugène Scribe. En ayant consulté la lettre, j'ai vu qu'il parlait de _la None_ (orthographié comme ceci dans sa lettre), et cela correspond à un opéra composé par H. Berlioz avec un livret d'Eugène Scribe.

**Comment by SjdkC** [comment]
Merci beaucoup pour ton retour Fanny !

3. Entendu, en effet je pense que c'est la bonne chose à faire.
4. C'est possible ! En tout cas, je n'ai pour le moment pas d'autre hypothèse...
5. Je n'avais pas du tout envisagé qu'il puisse s'agir d'un nom de personne : avec tes explications, cela fait parfaitement sens ! Merci encore :)

**Comment by Lienceard** [comment]
Bonjour Cécile,

1. Je lis bien petit-opéra.
2. Je pencherai plus pour "les modistes" étant donné le contexte.
3. Je suis désolée. Je ne peux pas te renseigner car je n'ai pas rencontré ce cas de figure.
4. Je lis également l'ours.
5. Je pense que c'est bien "scribe" d'après la graphie du "s".

**Comment by SjdkC** [comment]
Merci beaucoup Lien pour tes réponses !
Nos interprétations semblent se rejoindre, ce qui est rassurant.

**Comment by SjdkC** [comment]
Je ré-ouvre cette issue pour informer @Lienceard, en charge de la relecture de cette lettre, qu'elle est prête à être relue. 

De plus, je signale quelques points d'attention :

1. Image 2, ligne 3

![Capture d’écran du 2022-01-06 18-11-46](https://user-images.githubusercontent.com/92724884/148427261-f2fbfbc1-707f-49d8-8cda-9489a49f86ac.png)

J'ai retranscri "M. Pasquier" ; le symbole après le "M" peut-il vraiment être interprété comme un point ?

3. Image 2, ligne 4

![image](https://user-images.githubusercontent.com/92724884/148428849-35c5f070-ff08-4747-a99a-43bdfd8f1e5c.png)

Je lis "Dieu ne ne le sait pas". Vois-tu également un "ne" dédoublé ?

3. Image 2, ligne 5
Le doute que j'ai signalé dans le premier message de l'issue persiste. Je lis toujours "l'ours", cependant.

4. Lettre 2, ligne 16

![image](https://user-images.githubusercontent.com/92724884/148429089-c67d2211-b80a-4d83-9600-ae937bae2d0b.png)

Malgré la petite taille du tiret, vu le contexte, j'ai interprété le signe après "Mme Nathan" comme étant un tiret d'incise. Je l'ai donc retranscrit par un tiret cadratin. Penses-tu également qu'il s'agit d'un tiret d'incise ?

5. Lettre 1, ligne 22

![image](https://user-images.githubusercontent.com/92724884/148429702-356234a9-9306-4a3d-a5a1-8cf41df5f233.png)

Dans la même veine, j'ai ici aussi interprété le signe comme étant un tiret d'incise, mais cela peut se discuter au vue du contexte (après une citation).

6. J'ai parfois eu quelques doutes sur la retranscription des accents (grave ou aigu ?). Je me suis parfois basée plus sur le tracé que sur l'inclinaison de l'accent, mais peut-être auras-tu par moment des interprétations différentes. N'hésite pas à me le dire si c'est le cas !

Merci par avance pour ta relecture et tes retours ! :)

**Comment by SjdkC** [comment]
Bonsoir,

Je réagis ici à la PR #22.

Tout d'abord, merci Lien pour ta relecture ! Point par point :
- J'avais en effet oublié de signaler le soulignement de la date, je te remercie de l'avoir relevé.

- Ok pour l'accent de la ligne 2 et celui de la ligne 14.
- Je me range à ton avis pour le "ainsi" de la ligne 6.
- Ok pour prendre en compte le "gribouilli" en interligne (rajout de la ligne 21). J'avais décidé de l'ignorer, mais après tout pourquoi pas ! Je rajouterai une ligne sur eScriptorium.
- Ligne 4, j'ai en effet hésité, mais je ne suis pas sûre que la retranscription de l'espace soit indiquée. Je m'explique : dans ce contexte, il me semblerait que, malgré la rature, il s'agit d'un tiret d'union entre commis et voyageur (le mot "commis-voyageur" existe). Du coup, je pense que, de la même façon que nous n'avons pas rajouté d'espaces avant les points même lorsque la graphie de Berlioz pouvait en suggérer un, il n'est pas forcément indiqué d'en rajouter un ici. Qu'en penses-tu ?
- J'ai aussi une réserve quant à ce que tu proposes pour la ligne contenant "à Grenoble". En effet, j'ai choisi de considérer ce mot, rajouté en interligne, comme étant sur sa propre ligne (je sais que Fanny a par exemple fait un choix différent – comme convenu, nous parlerons de cette inconstance dans le rapport final). Donc, dans eScriptorium, le tracé de la ligne est très court, de la taille des deux mots ; il ne fait pas la largeur de la page :
![image](https://user-images.githubusercontent.com/92724884/148655372-e3513c3f-9e31-4ee1-85f5-bab4ddcaaccc.png)
Sachant cela, il n'y aurait pas de sens de rajouter des espaces au sein de cette ligne. J'ai conscience que cela complique la lecture du fichier txt, mais il ne s'agit pas du format principal du rendu : les coordonnées de la ligne seront de toute façon conservées par le XML ALTO. Or, à mon sens, l'ALTO et le fichier texte doivent contenir les mêmes informations ; je ne pense donc pas que rajouter des espaces seulement dans le fichier texte (mais pas dans eScriptorium, donc pas dans l'ALTO) soit pertinent. Cependant, je comprends pourquoi tu as fait cette proposition !

Merci encore ! :)

**Comment by Lienceard** [comment]
Bonjour Cécile, 

Je suis désolée de n'avoir pas pû te répondre plus tôt. Je n'avais pas encore fini de relire la transcription de l'image 2.
Pour la ligne 3, j'ai pensé  "Me" pour "Maistre" car un "." aurait été plutôt sur la ligne qu'au dessus.
Pour la ligne 4, je lis la même chose que toi. C'est vraisemblablement une erreur de l'auteur. 
Pour la ligne 5, je lis aussi "l'ours". Cela peut-être un surnom qu'il donne à une personne qui existe ou bien un personnage d'un de ses opéras. Je pencherais plutôt pour la première solution.
Pour la ligne 16, j'ai préféré mettre un point au regard du contexte. Je pensais qu'après il changeait de sujet en parlant de Mme Weber. 

en espèrant que mes propositions puissent t'aider,

Bonne fin de journée.

**Comment by Lienceard** [comment]
suite à tes retours sur ma relecture de ta transcription de l'image 1,j e pense aussi qu'on peut ne pas mettre d'espace avant le tiret qui est situé entre commis et voyageurs.

**Comment by SjdkC** [comment]
Bonsoir ! 

Ne t'en fais pas !
Comme nous en avons parlé à trois, j'ai fait quelques modifications par rapport aux accents, mais autrement je te remercie vivement pour tes retours et tes propositions ! J'ai donc accepté la majorité de tes propositions, j'ai validé les PR, reporté les changements dans eScriptorium et importé les nouvelles versions XML ALTO.
Merci encore ! :)
