### ISSUE TITLE
rédaction du rapport 

### ISSUE THREAD

**Issue by Lienceard** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#18]
Bonjour à toutes,

Je vous souhaite mes meilleurs voeux pour l'année qui arrive! 

La date de rendu de devoir approche, il faudrait que nous commencions la rédaction du rapport final à rendre au format ODT.
Il faudrait peut-être réfléchir à la ou les personnes en charge de rédiger le rapport et la manière dont on va organiser le dépôt sur Git Hub. 

On pourrait faire un plan détaillé du rapport en reprenant le README et les discussions que nous avons eu dans les issues. Ce ne serait qu'une version de départ qu'il faudrait enrichir des nouvelles discussions que nous aurions eues...
il faudrait faire ensuite une pull request de ce plan détaillé afin que les membres du groupe puissent soumettre leurs corrections.
Toutefois j'ai peur que dans une issue - comme nous l'avions fait pour le plan README - qu'il n'y ait pas assez de place pour mettre le plan détaillé. Cela risque également de ne pas être trop commode pour la lecture....

C'est pourquoi je me demandais s'il ne fallait pas créer une branche "Rapport" sur laquelle on mettrait le plan détaillé, une version au format TEXT du rapport, une autre version (mise en forme) en format odt. 

De la même manière, je pensais qu'on pourrait utiliser les pull requests pour la version TEXT
Après la validation du plan du rapport, je pense qu'il serait préférable d'avoir une version TEXT. Cela me paraît plus pratique pour faire les modifications et les soumettre via des pull requests qu'un format ODT. Par ailleurs, il y aura des parties communes et des parties individuelles à rédiger.

Cette version TEXT finalisée serait ensuite reprise dans un fichier ODT par la personne qui se chargera de mettre en forme le rapport et de le mettre sur la branche main.

Si cela peu vous soulager dans vos travaux respectifs, je me propose  pour la rédaction d'un plan plus au moins détaillé que vous pourrez par la suite modifier. En fonction du plan, je pense qu'on verrait mieux pour se répartir après la rédaction des différentes parties.

Qu'en pensez-vous?

**Comment by SjdkC** [comment]
Bonjour Lien,

Merci beaucoup, meilleurs voeux ! :D

Je suis d'accord, nous devons commencer à penser au rapport. Je remets pour rappel les consignes du rapport pour que nous ne les perdions pas de vue :

>  Ce rapport se concentrera sur une présentation des données sources, leur relation aux jeux existants de données, les difficultés qu’elles peuvent présenter, sur l’expérience (ses choix, ses défauts, et ses échecs), s’intéressera aux projets semblables. Il sera rédigé en LaTeX ou ODT, avec bibliographie.

Le format ODT me va tout à fait (le format LaTeX a aussi des qualités, mais je pense qu'il nous rajouterait une charge de travail, étant donné que nous ne maîtrisons pas encore tout à fait LaTeX...).

Pour le plan, je pense en effet que nous devons nous baser en partie sur nos issues pour identifier les problèmes qui ont été les nôtres. Il me semble notamment important de documenter nos choix de normes de transcriptions. Au vue des consignes, je pense que nous aurons également un petit travail de documentation à faire, afin de mettre en contexte notre travail et notre jeu de données (et pour dégager de la bibliographie !)

Concernant l'organisation que tu proposes, je pense que nous pouvons peut-être faire plus simple. En effet, si l'utilisation de Git(hub) me paraît utile et justifiée pour s'assurer de la qualité de nos données de transcription, il me semble que ce n'est peut-être pas l'outil le plus adapté pour rédiger un rapport. Il me semblerait plus pertinent d'avoir recours à un service tel que Google Docs, qui me semble plus adapté à un travail de rédaction pure. Le fichier pourrait ensuite être ajouté sur le dépôt (mais devons-nous vraiment joindre ce rapport au dépôt, ou pouvons-nous le faire parvenir d'une autre façon ?). Je ne pense pas que les consignes du devoir nous imposent d'utiliser uniquement Github, d'autant plus si un autre outil numérique nous semble plus pertinent pour telle ou telle tâche. Que pensez-vous de cette solution ?

Merci à toi de te porter volontaire pour proposer un plan !  Je pense de toute façon que nous n'avons pas besoin d'un plan extrêmement steructuré, tant que son déroulé est logique. Il devrait donc nous être assez aisé d'y insérer d'autres points par la suite, si besoin !

**Comment by FannyLbr** [comment]
Bonjour Lien, 

Meilleurs voeux également ! :) 

Je suis d'accord aussi, il va falloir commencer la rédaction du rapport. 
(Merci Cécile pour le rappel des consignes). 

Je suis ok aussi pour le format ODT.

Je vous rejoins pour la création du plan détaillé. L'analyse de nos issues sera un bon point de départ. Et oui, je te rejoins Cécile, il faudra faire un travail de documentation.

En ce qui concerne l'organisation, effectivement, j'ai peur que ce que tu proposes, Lien, soit un petit peu compliqué. J'ai peur que l'on se perde entre les PR sur les lettres et les PR concernant le rapport. D'autant plus que la rédaction d'un rapport doit pouvoir être suivi et modifié très régulièrement par chacune d'entre nous, donc pour éviter les erreurs de transmission du fichier, je pense aussi que l'utilisation de Google Docs pourrait être un bon moyen pour la rédaction du rapport. Comme le dit Cécile, rien ne nous empêchera de mettre ce rapport finalisé sur Github ensuite. Et je pense également que nous sommes libres de choisir l'outil numérique le plus pertinent pour les tâches à effectuer.

Merci Lien pour la rédaction du plan ! Si tu as besoin d'aide, n'hésite pas.

**Comment by Lienceard** [comment]
Je vous remercie pour vos retours.
Je vous propose de faire le plan détaillé ainsi que le rapport sur Google Docs. On pourra ensuite l'exporter au format odt (c'est vérifié).
On aura alors plus qu'à l'ajouter sur la branche "main". 
Je vous partagerai dès que possible le plan.

**Comment by Lienceard** [comment]
Bonjour à toutes,

Une première ébauche du plan est disponible dans le Google Drive à l'adresse ci-dessous.
https://docs.google.com/document/d/1oc3w_p80UIucR8G36g99MGirDXTfPvh5jfIeA5DYZhY/edit
Je vous laisse en prendre connaissance et y apporter des corrections, si vous en jugez la nécessité.

Bonne fin de journée.

**Comment by SjdkC** [comment]
Merci à toi Lien !

**Comment by FannyLbr** [comment]
Bonjour Lien, 

Merci beaucoup pour cette ébauche de plan.

**Comment by Lienceard** [comment]
Voici le nouveau lien pour la rédaction du rapport : https://docs.google.com/document/d/1F2dvYSGH4JAdwaNXCV4xaL2J6kI1jkXGjJnoN7bhZ10/edit
Bonne rédaction!

**Comment by Lienceard** [comment]
Bonjour à toutes,

Nous sommes actuellement en train de rédiger le rapport à rendre.
Il faudrait peut-être que nous pensions à sa relecture.
Je vous soumets la proposition suivante. Nous pourrions reprendre la même organisation que pour la relecture des transcriptions. Ainsi Fanny relirait ma partie, Cécile la partie de Fanny, et moi la partie de Cécile.
De cette manière, la relecture du rapport serait réalisée plus rapidement.
L'ensemble des membres du groupe pourra bien-sûr jeter un coup d'oeil à l'ensemble du rapport.

Qu'en pensez-vous ?

**Comment by SjdkC** [comment]
Bonsoir Lien,

Concernant le rapport, je pense qu'il est quand même important que tout le monde le relise dans son ensemble, afin de s'assurer de la cohérence globale et d'éviter les redites, mais aussi pour être sûres que nous soyons toutes d'accord avec son contenu. Je ne pense donc pas qu'il soit forcément utile d'assigner telle partie à telle personne pour la relecture.

Je ne pense pas qu'une relecture globale nous prendra trop de temps, étant donné que le rapport est censé faire 2-3 pages environ.

**Comment by FannyLbr** [comment]
Bonsoir Lien, 

Je suis d'accord avec Cécile, il est préférable que tout le monde relise l'ensemble.

**Comment by Lienceard** [comment]
Bonsoir à toutes,

J'approuve pour la relecture de l'ensemble du rapport par l'ensemble du groupe.
