### ISSUE TITLE
proposition d'organisation de l'équipe pour la résolution des problèmes de transcription

### ISSUE THREAD

**Issue by Lienceard** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#2]
Bonjour à toutes,

Nous allons rencontrer très prochainement des problèmes de transcription avec les lettres de la correspondance d'Hector Berlioz.
C'est pourquoi je pensais à des pistes d'évolution de notre dépôt actuel. 
On pourrait créer une branche de travail commune sur laquelle on déposerait un dossier contenant l'ensemble des lettres en format pdf  et issues de Gallica. Ainsi chacune pourrait s'y référer quand l'une d'entre nous aurait un problème de transcription et demanderait de l'aide au groupe. 
On pourrait également créer une issue pour chacune des lettres avec laquelle nous rencontrerions des difficultés. Cela permettrait de ne pas démultiplier les issues à chaque problème de transcription rencontré. 

Merci par avance pour vos retours

**Comment by FannyLbr** [comment]
Cette organisation me convient très bien. J'ajoute juste une précision : en ce qui concerne les issues sur les problèmes de transcription, nous pourrions faire une issue par lettre et non par image. L'issue recensera alors tous les problèmes rencontrés sur la lettre entière (au total 3 images). Je pense que nous pourrons bien nous y retrouver comme cela. 
Pensons aussi à mettre un label à ce type d'issue, dans ce cas précis : "help wanted".

**Comment by SjdkC** [comment]
Concernant les issues, je pense en effet qu'il serait plus simple d'en créer une par lettre.

D'accord également pour le label.

Je propose aussi que l'on ferme les issues lorsque les problèmes actuels sont résolus, même si d'autres problèmes pourraient apparaître plus tard (dans ce cas, l'issue peut être rouverte en temps voulu !)

**Comment by Lienceard** [comment]
on peut reprendre la convention de nommage du dossier de chaque lettre pour nommmer notre issue

**Comment by FannyLbr** [comment]
Ça me va, et oui on reprend les conventions de nommage.

**Comment by SjdkC** [comment]
D'accord, dans ce cas cela donnerait "LettreID_JJ-MM-AAAA".

**Comment by FannyLbr** [comment]
Oui voilà parfait.

**Comment by Lienceard** [comment]
oui parfait
