### ISSUE TITLE
Création d'un tableau de gestion

### ISSUE THREAD

**Issue by SjdkC** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#3]
Bonjour à toutes,

Afin de faciliter la répartition du travail et de garder trace de nos avancées, je propose de créer un tableau de gestion. Les outils intégrés de Github ne me semblent pas les plus adaptés à nos besoins, donc je propose la création d'un fichier markdown. Ce fichier aurait l'avantage d'être aisément modifiable depuis Github, ce qui faciliterait le travail pour toutes.

Il me semblerait pertinent d'inclure dans le tableau :
- Un identifiant pour chaque lettre ;
- La date de la lettre  ;
- Son lien sur Gallica ;
- Son identifiant ark (pour faciliter l'import des images sur eScriptorium, par exemple) ;
- La personne en charge de la lettre ;
- Le nombre estimé de lignes de la lettre (afin de s'assurer que chacune transcrit environ 100 lignes, selon les consignes du devoir) ;
- Le nombre d'images (images, et non pages ou feuillets, pour mieux coller à la logique d'eScriptorium qui permet de travailler image par image) ;
- Des colonnes segmentation, transcription, relecture, validation, afin de savoir où chacune en est dans l'avancement de ses travaux. Pour que ce soit plus simple, je propose d'inscrire par exemple "1 2" dans le colonne segmentation si les images 1 et 2 ont été segmentées.

Si cela vous convient, je propose de créer le tableau depuis un générateur de tableaux en Markdown afin de gagner en efficacité, puis de créer le fichier sur Github.

Merci par avance pour vos retours !

**Comment by Lienceard** [comment]
Cela me convient parfaitement.

**Comment by FannyLbr** [comment]
Parfait pour moi aussi ! Merci !

**Comment by SjdkC** [comment]
Très bien, j'ai créé le tableau !
