### ISSUE TITLE
Choix export et nommage des fichiers de transcription

### ISSUE THREAD

**Issue by FannyLbr** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#4]
Il faudrait que nous nous mettions d'accord sur deux points : 

- **le format d'export des fichiers d'eScriptorium** : je vous proprose d'exporter les fichiers à la fois en format text et en format alto. Comme nous ne savons pas quelle utilité nous en aurons après, il est préférable de l'avoir sous deux formats différents. Nous pourrons affiner cela par la suite en fonction de nos besoins.

- **le nommage de ces fichiers**: je vous propose de nommer nos fichiers de transcription de façon uniforme. Que pensez-vous de : "Lettre ID - date - transcription" ?

**Comment by Lienceard** [comment]
J'approuve ta proposition.

**Comment by SjdkC** [comment]
D'accord, cela me semble bien !

**Comment by Lienceard** [comment]
il faudrait également ajouter le numéro des images dans le nommage des fichiers afin de savoir laquelle image on a transcrit.
Lettre-ID-date-transcription-numéro d'image

**Comment by SjdkC** [comment]
Après réflexion, peut-être vaut-il mieux faire des exports en format texte brut pour le moment, afin de faciliter la relecture et l'entraide sur les transcriptions. Je ne pense pas que le format XML ALTO soit nécessairement utile à ce stade, même s'il serait bon de l'inclure en fin de projet (étant donné qu'il conserve le lien entre le texte et l'image).

**Comment by FannyLbr** [comment]
Oui effectivement c'est mieux. On fait comme cela alors.

**Comment by Lienceard** [comment]
le nommage des fichiers est un peu ambiguë car nous ne savons pas si "transcription" fait référence à la transcription d'eScriptorium non corrigée ou bien à celle corrigée par nos propres soins selon les normes de transcription qu'on aura définies.

**Comment by SjdkC** [comment]
En effet ! De manière plus globale, je propose que nous adoptions des conventions / une même organisation pour les dossiers également, afin de mieux nous y retrouver. Je propose cette organisation :

- Pour chaque lettre, un dossier nommé : “Lettre ID - date”.
- Dans ce dossier, les transcriptions terminées au format .txt nommée : “Lettre ID-date-transcription-numéro d'image”.
- Les images de la lettre, réunies dans un fichier unique nommé : “Lettre ID - date”.
- Un sous dossier nommé “Transcriptions brutes” avec dedans les transcriptions brutes d’eScriptorium (afin de rendre compte du travail de transcription réalisé, ainsi que de l’efficacité initiale du modèle utilisé).

Et, une fois la transcription définitivement terminée et corrigée :

- Les transcriptions au format ALTO nommées “Lettre ID - date - ALTO - numéro d'image”.

Qu'en pensez-vous ?

**Comment by Lienceard** [comment]
Je suis d'accord pour les conventions de nommage. 
Toutefois, il faudrait préciser davantage la manière d'écrire la date.
Par exemple pour nommer le fichier contenant les images de la lettre datant du 4 novembre 1823, on pourrait faire la chose suivante: Lettre-1-04-11-1823

**Comment by FannyLbr** [comment]
Cela est parfait pour moi Cécile. Juste, en ce qui concerne les fichiers de transcription brute d'eScriptorium, comment on les nomme ? Est-ce que cela irait : "Lettre-ID-date-transcriptionBrute-numéro d'image" ?
Aussi, je pense que nous devrions utiliser les underscore plutôt que les tirets, cela serait plus clair. Qu'en pensez-vous ?

**Comment by FannyLbr** [comment]
Ok ça me va Lien pour la convention des dates.

**Comment by Lienceard** [comment]
oui je suis d'accord avec toi Fanny

**Comment by SjdkC** [comment]
D'accord avec toi pour les fichiers de transcription brute, j'avais en effet oublié de l'indiquer.

Le format de date me semble bien (nous nous adressons avant tout à des francophones). Je propose du coup d'incorporer les tirets du bas (et de supprimer l'espace entre Lettre et l'ID, si cela vous va ?) mais de peut-être garder les tirets du milieu à l'intérieur des dates. 

Ce qui donnerait par exemple : LettreID_JJ-MM-AAAA_transcriptionBrute_numéroDImage

**Comment by Lienceard** [comment]
oui c'est mieux. Cela permet de différencier l'ID de la lettre et sa date.

**Comment by FannyLbr** [comment]
Parfait pour moi !

**Comment by SjdkC** [comment]
Très bien, nous allons pouvoir formaliser tout cela dans un compte-rendu !
