### ISSUE TITLE
Gestion finale des branches

### ISSUE THREAD

**Issue by FannyLbr** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#46]
Bonjour les filles,

J'ouvre cette issue, car avant de rendre notre projet, je pense qu'il faudrait faire du tri dans les branches créées.

Nous avons mis l'ensemble des fichiers sur la branche main. Gardons-nous aussi les branches Cecile, Lien, et Fanny ? Je pense que cela ne serait pas dérangeant de les laisser. Mais si nous les gardons, nos documents ne sont pas nommés de la même façon que sur la branche main (ajout du 0 devant l'ID), il faudra peut-être renommer ces documents pour que toutes les branches soient homogènes avec main.

Pour ce qui concerne la branche dev, j'imagine que nous allons la supprimer, car elle nous a servi seulement d'étape pour merger sur main. Êtes-vous ok ?

J'ajoute aussi également qu'il ne faudra pas oublier de supprimer toutes les branches créées lors des PR lorsque celles-ci seront fermées (je pense à la branche readme, relecture_exports_conventions_nommage, relecture_normes, relecture_readme).

**Comment by SjdkC** [comment]
Bonjour !

Cela ne me dérangerait pas de garder les branches de travail Cecile, Lien et Fanny, mais il me semble peut-être inutile de passer du temps à renommer tout nos fichiers (ce qui est quand même plutôt chronophage), alors que ces branches ne seront normalement pas consultées... Si les différences de noms te perturbent, nous pouvons peut-être supprimer ces branches (qui n'apportent peut-être pas grand chose au rendu final), ou choisir d'ignorer les différences de noms.

D'accord avec toi pour la suppression de dev et des branches restantes liées aux PR ! :)

**Comment by Lienceard** [comment]
Bonjour,

Je suis d'accord avec Cécile pour conserver nos branches de travail. Elles permettent de garder une trace de l'organisation de notre dépôt et,en cas de problème, de pouvoir avoir une autre copie de nos travaux respectifs. Il me semble également pas nécessaire de renommer nos fichiers, sachant que ce sont des branches de travail et que nous avons expliqué dans le rapport la raison pour laquelle nous avons dû changer le nommage des fichiers en fin de projet. Je suis d'accord pour supprimer les branches créées lors des pull requests et celle "dev".

**Comment by FannyLbr** [comment]
D'accord avec vous. Gardons les branches de travail (Lien Cecile Fanny) au cas où, mais ne changeons pas les noms de fichiers. Effectivement Lien, tu as raison, nous le notifions dans le rapport et ce ne sont que les branches de travail, donc ne changeons rien. 

Je me charge de supprimer les branches des PR fermées et "dev".
