### ISSUE TITLE
Que vont devenir les liens du Readme après le transfert de propriété du dépôt ?

### ISSUE THREAD

**Issue by SjdkC** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#47]
Bonjour à toutes !

Le projet touche à sa fin et nous allons bientôt devoir en transférer la propriété à l'organisation [PSL-Chartes-HTR-Students](https://github.com/PSL-Chartes-HTR-Students). Je pense que ce transfert risque de poser problème concernant les liens internes que nous avons formalisé dans le Readme, de même que dans le fichier du tableau de gestion. En effet, le transfert de propriété devrait changer l'url du dépôt, ce qui cassera sans doute les liens internes.

Il nous serait peut-être possible de changer les liens fautifs une fois le transfert de propriété effectué, mais je ne sais pas si cela est très correct, étant donné que le transfert de propriété équivaut à une remise pour évaluation (il est alors peut-être malvenu de modifier notre travail après cette remise). De plus, le problème se poserait à nouveau si le dépôt est à nouveau transféré à l'avenir, pour une raison ou une autre.

Pour ces raisons, je propose la suppression de ces liens internes. Cela ne me semble pas nécessairement dommageable, puisque par ailleurs nous expliquons bien l'architecture de notre dépôt.

Qu'en pensez-vous ?

**Comment by Lienceard** [comment]
Bonsoir, 

Je valide ta proposition.
En effet, il faut mieux prendre ces précautions. Sinon, cela risquerait de faire penser à un manque de sérieux de notre part.

**Comment by FannyLbr** [comment]
Bonjour, 
Ok avec ta proposition Cécile. Il est préférable de les enlever pour éviter des problèmes ultérieurs.

**Comment by SjdkC** [comment]
Très bien, je vais procéder !
