### ISSUE TITLE
réflexion normes de transcription

### ISSUE THREAD

**Issue by Lienceard** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#5]
Bonjour à toutes,

J'ai commencé à corriger les transcriptions obtenues avec eScriptorium. 
Je vous propose de mettre en majuscule la première lettre des prénoms et noms de personnes, des noms de villes et du premier mot commençant les phrases.
Je vous propose également de conserver l'accentuation et la ponctuation de l'auteur même si les phrases sont assez longues.

**Comment by FannyLbr** [comment]
Bonjour Lien, 
J'ai commencé également à corriger la transcription brute de la lettre 3, je peux donc réagir à ton message. Je suis d'accord avec les règles que tu proposes, cela me semble bien, car cela nous permet d'être au plus proche des lettres.

Je me suis posé trois autres questions : 
- Est-ce qu'il faut restituer l'accentuation lorsqu'elle manque ? (par ex, un "a" à corriger en "à" si c'est une préposition, c'est un des cas que j'ai rencontré).
- Est-ce qu'il faut restituer les traits d'union lorsqu'ils manquent ?
- Est-ce qu'il faut corriger les mots qui ont une faute d'orthographe ou une orthographe particulière (cela peut parfois être une orthographe ancienne, il faut faire attention à cela) ?

**Comment by FannyLbr** [comment]
J'ajoute deux autres questions : 
- Faut-il représenter d'une certaine façon les mots soulignés ? Il me semble que comme eScriptorium ne les prenait pas en compte nous avions conclu qu'on ne les représenterait pas, mais je préfère m'en assurer auprès de vous une nouvelle fois. 
- À propos des feuillets où il y a le destinataire et l'adresse, est-ce qu'il faut prendre en compte les tampons/cachets ?

**Comment by SjdkC** [comment]
Bonjour à toutes,

Afin de réfléchir aux problématiques de transcription, je me suis renseignée un peu, et je pense qu'il serait bon d'effectuer une transcription la plus fidèle possible. Je me base par exemple sur la ressource suivante :

> Alix Chagué, Thibault Clérice, Laurent Romary. HTR-United : Mutualisons la vérité de terrain !. 2021. hal-03398740. https://hal.archives-ouvertes.fr/hal-03398740 

Cette publication définit trois critères permettant de "contrôler la qualité d'un jeu de données" : 

> - l'homogénéité des règles de transcription suivies pour produire ces données,
> - la fidélité de la transcription par rapport à l'image
> - et sa capacité à s'adapter aux objectifs d'un autre projet.

En ce qui nous concerne, je pense qu'il peut être intéressant de garder à l'esprit le deuxième point pour établir nos règles, mais n'hésitez pas à me dire si vous pensez à une autre approche. Cela me semble en tout cas en adéquation avec notre positionnement, qui est bien de produire des transcriptions, et non une édition. Il me semble en plus que c'est cette approche qui permettrait la meilleure réutilisation potentielle de notre travail.

Si l'on suit ce principe, je propose donc :

1. **Restitution des majuscules** : je pense qu'il serait préférable de ne pas restituer les majuscules même si elles sont absentes en début de phrase ou de nom propre.

2. **Accentuation et ponctuation** : d'accord pour conserver celles de l'auteur.
3. **Restitution de l'accentuation** : je propose là aussi de ne pas la restituer.
4. **Traits d'union** : idem.
5. **Orthographe ancienne** : là encore, je pense qu'il vaut mieux conserver l'orthographe de l'auteur.
6. **Mots soulignés** : en effet, il me semble qu'eScriptorium ne permet pas (encore ?) de les indiquer comme tels. Je pense donc que nous pouvons ignorer le soulignement.
7. **Cachets** : puisque notre but est avant tout de transcrire ce qu'a écrit Berlioz, je ne suis pas sûre qu'il soit utile d'inclure les tampons/cachets (mais j'imagine que ça se discute...)
8. **Eventuelles abréviations** : là encore, je propose de ne pas les résoudre (les résoudre pourrait en plus poser d'autres problèmes : si une résolution paraît fautive, difficile de savoir si c'est la résolution en elle-même qui l'est, ou la transcription/l'HTR...).

Qu'en pensez-vous ?

Dans tous les cas, quand nous nous serons mis d'accord sur des règles, je pense que nous pourrons créer un fichier de synthèse pour les lister (quitte à compléter ce fichier au fur et à mesure si d'autres questions se posent !) :)

**Comment by Lienceard** [comment]
Bonsoir les filles,

Je suis d'accord avec toi Cécile. Il fait qu'on reste le plus proche possible du texte au risque de commettre des erreurs notamment au moment de la résolution des abréviations.
Toutefois pour les cachets on peut juste signaler leur présence en mettant tout simplement quelque chose comme ceci : [cachet] 
Car il me semble important de le signaler pour des raisons diplomatiques et que le lecteur sache que ce sont bien des lettres. 

Par ailleurs, pourrait-on formaliser les normes de transcription prochainement dans un fichier ? On pourrait le faire quand la première transcription de chacune de nos lettres est terminée et après qu'on ait résolu nos problèmes de transcription de certains passages ou bien maintenant...

Qu'en pensez-vous ?

**Comment by FannyLbr** [comment]
Merci Cécile pour cette proposition, justement, je voulais revenir sur cette issue aussi. 

J'ai réalisé une première correction des transcriptions brutes de mes lettres, et effectivement, cela m'a permis de me questionner plus précisément sur les choix de transcription. Je te rejoins Cécile sur ta proposition. En effet, les choix émis au début de cette issue avec Lien tendent plus vers une édition plutôt qu'une transcription à proprement parler.

Je suis donc ok pour les points 1 à 8 que tu proposes. 

Pour le point 7, je te rejoins aussi Cécile, je ne suis pas sûre non plus que cela soit utile de les transcrire puisque nous nous attachons essentiellement à l'écriture de H. Berlioz. Pour ma part, les tampons de mes lettres sont des "bribes" de tampons illisibles, je ne pense donc pas qu'ils apportent grand chose au lecteur, si ce n'est leur présence. À voir pour vos lettres.

Et oui, je suis d'accord avec toi Lien, il faudrait créer un fichier des normes de transcription assez rapidement pour pouvoir les appliquer au plus vite. Je vous conseille d'analyser toutes les difficultés de vos lettres (ou de faire une première correction de la transcription brute si cela est plus facile pour vous) afin que nous puissions établir des normes en fonction des cas que nous rencontrons.

**Comment by FannyLbr** [comment]
J'aimerais revenir sur quelques règles que nous avions rédigées dans le CR du 24 novembre. Nous avions dit : 

> Éléments lisibles/ illisibles : 
 

>  1) Transcrire les lettres effacées et que l’on devine. 

> 2) Transcrire un mot barré et lisible. 

>  3) Indiquer qu’on ne retranscrit pas lorsqu’un mot/ passage est illisible. 

> 4) Supprimer la ligne de texte ou transcrire une partie du mot mais pas l’intégralité et indiquer ce qu’on arrive pas à lire (utiliser des caractères de d’autres alphabets). 

Je suis toujours ok avec ces quatre points, mais il faudrait être plus précise. 

Le point 2 : appliquons-nous la même règle que pour les mots soulignés ? Autrement dit, faisons-nous le choix de transcrire le mot barré sans indiquer qu'il est barré ? Ou faisons-nous le choix de transcrire le mot barré en précisant qu'il est barré ?

Le point 3 : comment indiquer qu’on ne retranscrit pas lorsqu’un mot/ passage est illisible ? Faut-il mettre l'indication [illisible] par exemple ?

Le point 4 : il faudrait se mettre d'accord sur les caractères à utiliser pour le cas où on n'arriverait pas à déchiffrer l'écriture.

**Comment by SjdkC** [comment]
Merci Fanny d'avoir soulevé ce point, je voulais justement revenir aussi sur le cas des rature et des mots illisibles.

A mon avis, le point 3 et le point 4 se rejoignent. Je serais plutôt partisane d'utiliser des caractères d'un autre système d'écriture pour indiquer qu'un mot nous résiste toujours en fin de travail. Cette proposition avait été évoquée par M. Clérice en cours, et je la trouve plutôt adaptée, étant donnée qu'elle permet de désambiguïser notre notation. En effet, quelqu'un qui lirait notre transcription pourrait penser que `[illisible]`, par exemple, a vraiment été écrit par Berlioz dans sa lettre. Je propose par exemple d'utiliser à la place le hiragana japonais `か` (unicode `U+304B`) qui sert à marquer une interrogation, mais n'hésitez pas à proposer autre chose.

Dans l'hypothèse où nous adoptons ce système, il resterait à savoir si nous utilisons ce caractère pour représenter une lettre illisible, un mot illisible, ou un passage illisible. Personnellement je serais plutôt d'avis de l'utiliser pour représenter un mot entier. Il pourrait alors être utilisé plusieurs fois à la suite si un passage entier nous résiste. Cela nous permettrait également d'éviter d'avoir à éliminer une ligne entière en cas de passage illisible (point 4). Cependant il me semble aussi possible d'utiliser un caractère pour chaque lettre qui nous résiste, mais dans ce cas cela peut poser d'autres problèmes : ce système supposerait que l'on arrive à déterminer le nombre exact de lettres dans un mot qui nous résiste, ce qui n'est pas forcément évident puisque, précisément, le mot serait difficile à lire.

Concernant le point 2 (mot barré), j'avoue ne pas trop avoir réellement de proposition pour l'instant, mais je vais y réfléchir.

Par ailleurs, concernant les cachets, je suis assez d'accord avec Fanny : à mon avis ils sont annexes à notre travail, et nous effectuons une transcription, pas une édition diplomatique.

**Comment by Lienceard** [comment]
Je suis d'accord pour l'utilisation d'un caractère d'un autre système d'écriture pour une lettre, un mot, un passage illisible. 
Il faudrait peut être déterminer le nombre de fois qu'on le met pour indiquer si c'est une lettre, un mot, un passage...
Je vous fais la proposition suivante :

 か = une lettre
 か か = un mot
 か か か  = un passage

Je ne sais pas trop pour les mots barrés. Je pensais qu'exceptionnellement on pourrait mettre "mot barré" ou "phrase barrée" entre crochets après le passage en question. Mais cela risque de tromper le lecteur... Il faudrait peut être demander à nos camarades de promotion pour avoir plus d'idées...

Par ailleurs, je rencontre des mots qui sont collés ensemble alors qu'ils ne devraient pas l'être... je pensais les laisser et ne pas les séparer étant donné qu'on souhaite être le plus fidèle au texte.

Si nous souhaitons ne pas prendre en compte le cachet que faisons-nous pour la signature ? Si nous choisissons de ne pas transcrire le cachet ou signaler sa présence, il faudrait peut-être faire la même chose avec la signature afin de garder une certaine cohérence dans nos choix de normes de transcription.
Dans le cas où nous choisissons de transcrire la signature, il faudrait peut-être ouvrir une issue pour réfléchir et décider de la méthode à utiliser. En effet, lors de mon premier essai, eScriptorium ne la pas prise en compte et je ne sais pas s'il est possible de la transcrire

**Comment by Lienceard** [comment]
Par ailleurs, pour les gribouillis peut-on utiliser un caractère d'un autre système d'écriture ? 
Par exemple, on pourrait utiliser le même système d'écriture que pour les passages illisibles mais en utilisant un autre caractère.

**Comment by FannyLbr** [comment]
Oui, c'est vrai, vous avez raison, c'est une très bonne idée d'utiliser un caractère d'un autre système d'écriture comme le hiragana japonais, comme cela il n'y aura pas d'ambiguïté. Adoptons donc ce caractère pour les lettres/mots/ passages illisibles. 

Lien, ta proposition est plutôt bien, mais pour la représentation d'une lettre illisible, je rejoins l'avis de Cécile sur le fait que parfois nous ne pouvons pas savoir le nombre réel de lettres manquantes. Par exemple, si un mot commence par "c" et que la suite manque il est difficile de déterminer le nombre de hiragana à mettre. Peut-être pouvons-nous plutôt faire comme ceci : 

- か = un mot (exemple : "Je n'ai か compris").

- か か = un passage (exemple : Je かか").

- [lettre]か[lettre] = une/plusieurs lettre(s) illisibles. (exemple : Jか n'ai pかs compかs"). 

Oui Lien, je pense que c'est la bonne solution, si les mots sont collés, laisse-les coller. 

De quelle signature tu parles Lien ? "H. Berlioz" ou de cette "chose" ![Capture d’écran de 2021-12-29 19-42-34](https://user-images.githubusercontent.com/92677204/147693617-6805e1ad-76eb-49bb-837b-422bb609e545.png) ?

Pour ce qui concerne les mots barrés, effectivement, pourquoi ne pas utiliser un caractère particulier aussi ? Mais dans ce cas-là, il faudrait faire la même chose pour les mots soulignés, non ? J'ajoute aussi que pour les mots barrés, il faudra faire la distinction entre les mots barrés lisibles et les mots barrés illisibles (j'imagine que quand tu dis "gribouillis" Lien c'est pour ce dernier cas ?).

**Comment by FannyLbr** [comment]
Je reviens sur le point 1 du CR : 

> 1) Transcrire les lettres effacées et que l’on devine.

Est-ce que ce point ne va pas à l'encontre de notre parti pris d'être au plus proche du manuscrit ? Si la lettre reste apparente malgré le début d'effacement, je suis ok pour la transcrire, mais si la lettre est totalement effacée je ne suis pas sûre qu'il faille la restituer. Qu'en pensez-vous ?

**Comment by SjdkC** [comment]
Je vais numéroter les différents sujets afin que mon propos soit plus clair :

1. Concernant vos proposition d'utilisation des caractères, elles me semblent intéressantes, mais j'ai peur qu'elles puissent porter à confusion : si l'on a par exemple `か か `, il me paraît peu aisé de savoir si le manque correspond à deux mots, ou à un passage peu importe le nombre de mots qu'il comprend.
Une alternative à ma proposition serait de considérer que l'on peut utiliser un unique `か` quelle que soit l'importance du manque, mais cela ne me semble pas forcément beaucoup plus clair.
Je propose sinon que l'on se base sur la proposition de Fanny mais que, lorsqu'un passage entier est concerné, le nombre de `か` corresponde au nombre de mots concernés.

2. Concernant les mots barrés,, une idée pourrait être d'encadrer le mot avec un caractère spécial là aussi, ce qui rejoint la proposition de Fanny.

3. Pour ce qui est des mots collés, il me semble que dans la majeure partie des cas, il ne s'agit pas d'un choix conscient de la part de Berlioz, mais plutôt d'une particularité de son écriture.

Ainsi, ici, `que` et `tu` sont réliés/collés, mais il me semble malgré tout que nous pouvons dire que l'intention était d'avoir deux mots séparés.
![Capture d’écran du 2021-12-29 19-13-43](https://user-images.githubusercontent.com/92724884/147692030-a1058dd8-dfa2-4cb8-a974-50ce551a0b93.png)

Suivant cette logique, je ne pense pas que rétablir l'espace nous éloigne du texte ; mais je n'ai pas un avis ferme sur la question.

4. Je n'ai pas rencontré de signature dans mon travail. Même question que Fanny : Lien, veux-tu parler d'une signature de la lettre par Berlioz, ou d'un autre type de signature ? S'il s'agit de la signature de Berlioz, il me semble important de l'inclure. S'il s'agit d'un autre cas, peux-tu développer ?

5. Pour les "gribouillis", j'imagine qu'ils sont à rapprocher des ratures, mais sont, comme tu l'as dit Fanny, des mots raturés illisibles. Dans ce cas, si nous sommes d'accord pour encadrer les mots raturés avec un caractère particulier, peut-être peut-on utiliser ce même caractère, seul cette fois, pour signaler un passage raturé ?
Il est vrai que, dans ce cas, nous pourrions adopter le même système, mais avec un autre caractère là aussi, pour les passages soulignés. Cependant, il ne faudrait pas non plus multiplier indéfiniment les caractères... (Je pense néanmoins que trois caractères, un pour ce que l'on n'a pas réussi à transcrire, un pour les ratures, un pour les soulignement, reste raisonnable !)

6. Je suis plutôt d'accord pour ne pas restituer les lettres effacées .

**Comment by SjdkC** [comment]
Autre point, dans la continuité de nos débats :

![Capture d’écran du 2021-12-29 20-49-16](https://user-images.githubusercontent.com/92724884/147698393-e6cfd3a4-880b-4cc2-b3d8-3e5113abe73f.png)
 
Si des indications ont été rajoutées visiblement *a posteriori* (comme ici la référence en bas à gauche, ou le "34" en bas à droite), je pense qu'il vaut mieux réserver à ces indications le même traitement que pour les cachets (donc, ne pas les transcrire ?).

Qu'en pensez-vous ?

**Comment by FannyLbr** [comment]
Je reprends tes différents points pour te répondre Cécile : 
1. Oui, c'est vrai que cela peut porter à confusion... Si l'on part sur mon idée, nous pourrions partir du principe que lorsqu'il manque 2 mots ou plus, cela constitue un "passage" et donc on met "かか" (peu importe le nombre de mots manquants, sachant qu'on ne le sait pas forcément). Sinon, oui, nous pourrions utiliser un unique か pour tous les cas, je ne sais pas si cela sera plus clair par contre. 

2. Oui, je pensais à cela ! 

3. Je suis d'accord avec ce que tu dis, mais eScriptorium "voit" les deux mots collés, donc peut-être est-il préférable de les laisser coller ? Lien, qu'en penses-tu ?

4. Rien à ajouter. 

5. Oui, nous pourrions partir sur cette idée. Il faudrait se décider sur les caractères à employer. Et je te rejoins, je pense que 3 caractères différents, un pour ce que l'on n'a pas réussi à transcrire, un pour les ratures, un pour les soulignements, reste tout à fait faisable.

6. Ok.

**Comment by FannyLbr** [comment]
Pour les indications ajoutées _a posteriori_,  je suis tout à fait d'accord de ne pas les transcrire, puisque nous nous attachons essentiellement à la transcription de l'écriture manuscrite de Berlioz. Cela rejoint l'idée des cachets, oui.

**Comment by Lienceard** [comment]
Les pistes  d'amélioration proposées par Fanny me conviennent en ce qui concerne l'utilisation du hiragana. C'est pour moi très clair.
La photo que tu montres Fanny correspond bien à ce que j'entends par "signature". 
On pourrait réutiliser d'autres caractères japonais pour garder le système d'écriture. Mais si vous jugez qu'on risque de se perdre avec les caractères japonais, il fautdrait peut-être mieux changer complètement de système d'écriture. 
Pour revenir aux ratures, si j'ai bien compris la proposition de Cécile, on ne distingue pas les mots barrés lisibles et ceux illisibles.... 
J'avoue que dans la plupart des cas je rencontre des difficultés à les transcrire.
J'approuve l'utilisation des trois caractères spéciaux pour les ratures, les mots soulignés, les mots illisibles.
Je préfère personnellement laisser les mots collés car je ne trouve pas évident de juger si c'est volontaire ou non de la part de l'auteur...
Sinon, pour ma part je nai 'pas transcrit ce qui a été ajouté les marques au crayon à papier en bas des feuillets

**Comment by Lienceard** [comment]
Pour rebondir à la dernière remarque de Fanny, je suis d'accord pour qu'on n'indique pas les cachets, comme les ajouts au crayon à papier en bas des feuillets car ça était bien ajouté après le moment d'écriture de la lettre.

**Comment by SjdkC** [comment]
1. OK, je me range à votre avis pour utiliser `かか` pour un passage. Sur ce modèle, peut-être pouvons-nous également utiliser deux fois un symbole pour signifier une zone raturée illisible.

3. Je comprends votre avis sur les mots "collés", mais il me semble, dans les cas que j'ai rencontrés en tout cas, que l'espace est quand même signifiée par l'écart entre les mots, quand bien même il y a une ligature entre eux.

5. Très bien ! Par contre je ne sais pas trop quels caractères nous pourrions sélectionner ; le `か` a l'avantage d'être un caractère unique, et je pense que nous devrions garder ce principe pour les autres caractères.

> Pour revenir aux ratures, si j'ai bien compris la proposition de Cécile, on ne distingue pas les mots barrés lisibles et ceux illisibles....

Pas exactement (pardon, ce n'était peut-être pas très clair) : je proposais d'utiliser un même caractère pour représenter les ratures lisibles et les ratures illisibles, mais utilisé de manière un peu différente.
Ainsi, si par exemple le caractère retenur était `*`, une rature lisible serait notée `*mot*`, là où un passage raturé et illisible serait simplement notée `**` (sur le modèle des deux `か` utilisés pour signifier un passage que nous n'avons pas réussi à comprendre). Je ne sais pas si ma proposition est plus claire formulée ainsi !

Merci pour vos réponses concernant les ajouts _a posteriori_.

**Comment by SjdkC** [comment]
Un nouveau point me vient à l'esprit :

A certains moments, Berlioz utilise ce qui s'apparente à des tirets d'incise. Par exemple ici, après `suite` :

![image](https://user-images.githubusercontent.com/92724884/147793798-3de5fa0c-4c04-40c5-a4db-3485c4d605bc.png)

Je pense donc que nous ne devrions pas utiliser un tiret court (`-`) pour les représenter (Berlioz lui même a d'ailleurs tendance à faire un trait plus long que pour les traits d'union entre des mots). Je propose donc d'utiliser plutôt un tiret demi-cadratin (`–` , unicode U+2013), voire cadratin (`—`, unicode U+2014).

Qu'en pensez-vous ?

**Comment by FannyLbr** [comment]
1. Ok, on part là-dessus alors. 

2. Je comprends ton avis. C'est vrai que laisser les mots coller ne sera peut-être pas le plus lisible au final. Et je ne pense pas non plus que cela soit très dérangeant si nous faisons le choix de les décoller. Donc, après discussion, je suis ok Cécile. Lien es-tu d'accord ?

3. Oui, je suis d'accord. Mais est-ce que l'on reste sur l'alphabet japonais ou pouvons-nous prendre tout autre chose (alphabet grec ou signes divers tels que * \ ¿) ?

4. Très bonne remarque Cécile. J'ai déjà eu affaire à l'utilisation de ces deux tirets dans un projet précédent, et nous les avions utilisés en suivant les règles suivantes : 
- tiret demi-cadratin (– , unicode U+2013)  est employé pour marquer le changement d’interlocuteur dans les dialogues et devant les éléments des listes/ énumérations. 
- tiret cadratin  (—, unicode U+2014) est employé de part et d'autre d'une incise.

L'utilisation de ces deux types de tirets peut varier entre les projets puisque sur internet j'ai trouvé une utilisation inverse de ce que j'ai proposé. Mais je pense que pour notre cas les règles que je viens de détailler peuvent être bien. Nous aurions donc à utiliser le tiret cadratin pour le cas que tu mentionnes (incise).

**Comment by SjdkC** [comment]
2. Oui attendons l'avis de Lien !

3. Rien ne nous empêche de partir sur un autre système d'écriture, mais je pense qu'il vaut mieux éviter de les multiplier (on peut laisser tomber les hiragana s'ils ne sont pas pratiques !). J'ai un peu plus de réserve concernant les signes tels que `*\`, qui peuvent à mon avis être plus facilement confondus avec le contenu de la lettre.

4. Merci pour tes propositions sur les tirets, elles me paraissent très bien ! :)

**Comment by FannyLbr** [comment]
3. Au temps pour moi, je n'avais pas compris que "hiragana" correspondait au nom de l'alphabet, je croyais que c'était le nom du caractère que tu nous avais envoyé... (désolée, j'ai très peu de connaissance là-dessus ^^') Oui, dans ce cas-là, il faut rester sur le même système d'écriture. Mais est-ce que les différents caractères ne sont pas compliqués à différencier quand nous ne sommes pas familiers de cet alphabet japonais ?

**Comment by FannyLbr** [comment]
Au vu de l'avancée de cette issue, et comme nous avons abordé déjà beaucoup de règles (certaines sont approuvées, d'autres sont toujours en discussion), je me propose de rassembler dans un document les règles dont nous sommes sûres. Cela nous permettra peut-être d'y voir plus clair. Êtes-vous ok ?

**Comment by SjdkC** [comment]
3. Ne t'inquiète pas, c'est un détail, et je n'ai peut-être pas été très claire ! Oui, il est vrai que la reconnaissances des différents caractères peut poser problème... Ce n'est peut-être pas une solution idéale. Je vais essayer d'y réfléchir.

Tout à fait d'accord pour que tu rassembles les règles, merci beaucoup par avance !

**Comment by Lienceard** [comment]
Je suis d'accord pour décoller les mots.

J'avoue qu'un autre système d'écriture serait le mieux car si on continue à utiliser les caractères japonais, j'ai peur qu'on s'y perde. 
Ce que proposait Cécile me paraissait plus simple avec notamment l'utilisation de l'alphabet grec
Je ne sais pas le lire mais bon je pense qu'on devrait s'en sortir... Par contre l'alpha et le beta ressemble fortement si on n'y prend par garde au "a" et "b" de l'alphabet latin.
Après oui il ne faudrait pas démultiplier les systèmes d'écriture...

Mais je pense qu'il faut mieux garder les hiragana maintenant qu'on a décidé de les utiliser pour les passages illisibles.

J'ai également rencontré des tirets mais je ne sais pas si ce sont des tirets d'incise...Je pense que c'était plutôt le prolongement des "e" en fin de ligne. 

Sinon on peut adopter la proposition de Fanny avec les cadratins étant donné qu'elle l'a déjà utilisé auparavant dans d'autres projets.

Merci Cécile, c'est plus clair avec tes précisions sur les "ratures".

Par contre, est-ce qu'on va transcrire ou signaler la présence de la "signature" de l' auteur ? 

Merci à toi Fanny de rassembler les règles de transcription !

**Comment by Lienceard** [comment]
Bonjour à toutes,

J'ai rencontré à plusieurs reprises dans mes lettres le symbole d'une monnaie dont je pense être le franc. Je me demande  par quel symbole il va falloir le retranscrire... H. Berlioz parlait dans la lettre 2 de sommes dépensées avec l'argent donné par ses parents.

Je vous mets ci-dessous une capture d'écran pour que vous puissiez regarder.

![francs](https://user-images.githubusercontent.com/92690835/147853373-bde3b1a8-ce7b-487d-a9be-37c956cb7617.jpeg)

Par ailleurs, qu'avez-vous fait pour les mots en exposant ? 
Dans cet exemple (voir la capture d'écran ci-dessous), on retranscrirait "1r" ou "1" et "r" en exposant ? Je ne sais comment mettre un mot en exposant en dehors d'un logiciel de traitement de texte.

![er](https://user-images.githubusercontent.com/92690835/147853555-76cde727-5c75-4de0-9ef7-7b3e31863106.jpeg)


Je vous remercie d'avance pour vos retours.

**Comment by FannyLbr** [comment]
Lien, qu'appelles-tu la signature de l'auteur ? S'il s'agit de "H. Berlioz", oui, on la transcrit. 

Effectivement, cela doit être le franc. Je n'ai pas rencontré ce cas dans mes lettres, mais à ta place, j'aurai sûrement mis un "f". À voir avec Cécile. 

Pour les exposants, je ne sais pas trop quoi dire. Soit on fait le choix de les ignorer, soit l'on essaye de trouver un caractère qui pourrait les représenter. Par exemple, ce signe : ^ est parfois utilisé pour les exposants. (exemple : 1^r). Mais je ne sais pas si c'est une bonne solution.

**Comment by SjdkC** [comment]
- Je pense qu'il s'agit en effet de francs, mais la notation me fait penser au symbole utilisé pour la livre tournois (`lt`, ou dans sa version synthétique `₶`, unicode : U+20B6) pendant l'Ancien Régime. Même si la livre tournois a été remplacée par le franc, peut-être que l'usage de cette notation a été conservé ? D'autant que je ne crois pas que le franc disposait d'un symbole à proprement parler.

- Concernant les exposant, je les ai pour le moment retranscrits en ignorant l'exposant (donc en transcrivant "Mme", "2ème", par exemple).  Cette solution me semble peut-être plus simple que d'utiliser le symbole `^`, mais dites-moi ce que vous en pensez.

**Comment by FannyLbr** [comment]
- C'est vrai que le symbole ne ressemble pas vraiment à un "f" et peut faire penser au symbole de la livre tournois. Mais cela ne serait pas un peu étrange ? C'est peut-être à cause de la rapidité d'écriture que le symbole ne ressemble plus au "f" du franc. Pour ma part, j'ai dans une lettre le mot "franc". Mais à toi de trancher Lien, peut-être que le contenu de la lettre peut aider ?

- Oui, je te rejoins Cécile, c'est plus simple d'ignorer l'exposant.

**Comment by SjdkC** [comment]
C'est vrai que c'est étrange... Lien, pourrais-tu nous donner la référence des deux lignes qui figurent sur les captures d'écran ? Je pense que la meilleure qualité des images sur Gallica pourrait nous aider à mieux identifier le symbole !

**Comment by Lienceard** [comment]
Merci beaucoup pour vos retours.
Je pense qu'il faudrait mieux regarder directement les images de la lettre 2 dans le dossier "Lettre2_04-06-1827" sur la branche "Lien". 
il y avait parfois le mot "centimes" qui allait avec. 
Ce symbole je l'ai rencontré plusieurs fois aux lignes suivantes : 8, 9, 10, 11, 12, 13.
J'ai l'impression qu'il y a un "t" à la fin. Ce qui pourrait être bien "lt" comme disait Cécile.

J'approuve votre choix pour les mots en exposant. C'est plus simple.

**Comment by FannyLbr** [comment]
Pour information, j'ai créé un fichier "normes_transcription" où j'ai essayé de reprendre au mieux nos choix de transcription. (Vous devriez y avoir accès grâce à ma PR).

Pour faciliter ma rédaction, j'ai tranché sur le sujet du système d'écriture pour représenter les mots/passages illisibles/lisibles, j'ai fait le choix d'utiliser l'alphabet grec. Bien sûr, si cela ne vous convient pas, nous pourrons changer. 

N'hésitez pas à me dire si cela vous convient (ou pas). Ce document constitue seulement un premier "jet", nous pourrons l'améliorer et y ajouter des points si notre réflexion évolue. 

Toutefois, il ne faudra pas le clôturer trop tardivement, pour que nous puissions effectuer l'application de ces normes sur nos transcriptions respectives, avant de passer à la relecture.

**Comment by Lienceard** [comment]
Bonjour,

Merci beaucoup Fanny pour ton travail.
J'ai ajouté la norme pour les mots en exposant.
Sinon l'ensemble me convient parfaitement.
Oui, tu as raison. Il ne faudra pas tarder à finaliser le fichier.
De mon côté, je ne vois que le symbole de la monnaie à  ajouter.
Voyez-vous d'autres normes à ajouter ?

**Comment by FannyLbr** [comment]
De rien !

Merci à toi Lien, effectivement, j'avais oublié cette règle ! Et oui pour le symbole de la monnaie, il faut l'ajouter aussi.

Pour ma part, je ne vois rien d'autres à ajouter.

**Comment by SjdkC** [comment]
Lien, j'ai l'impression que le symbole monétaire est assez constant dans les lignes que tu as indiquées, donc je maintiens mon interprétation !

Merci beaucoup Fanny pour le fichier de synthèse. Il faudrait en effet ajouter le symbole de la monnaie une fois que nous serons d'accord, mais sinon tout me semble complet et clair !

**Comment by Lienceard** [comment]
Suite à vos retours,  je pense que la monnaie est bien  la livre tounois. Je rejoins Cécile pour l'utilisation de "sa version synthétique ₶, unicode : U+20B6". 
Peut-on à présent ajouter cette nouvelle norme au fichier ?
