### ISSUE TITLE
Problèmes sur eScriptorium

### ISSUE THREAD

**Issue by FannyLbr** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#6]
Bonsoir les filles, 

J'ouvre une nouvelle issue pour évoquer les problèmes rencontrés sur eScriptorium (segmentation/transcription automatique). 

Je rencontre quelques problèmes lorsqu'il faut segmenter puis transcrire des lignes verticales. J'ai trouvé les fonctionnalités adaptées à la segmentation de ces dernières (segmentation --> text direction : Vertical l2r), mais cela ne fonctionne pas. Aucune de mes lignes n'est prise en compte par la segmentation. Je ne sais pas si cela est dû à la qualité du manuscrit ou pas. De plus, lorsque je fais la segmentation à la main sur ces lignes verticales puis que je lance la transcription automatique, cela ne fonctionne pas non plus (aucun mot n'est transcrit). Est-ce que vous rencontrez ces problèmes ? 

Je vous mets ci-dessous les deux types de cas problématiques : 

- Lorsqu'il s'agit des feuillets avec destinataire et adresse, je corrige à chaque fois la segmentation entièrement à la main. Mais dès que je lance la transcription, cela ne fonctionne pas. Est-ce que vous avez ce problème ?

![Capture d’écran de 2021-12-23 20-13-53](https://user-images.githubusercontent.com/92677204/147283213-641f8a15-5e60-4e4a-9bb8-dd7d5759bc5f.png)

- Pour le cas ci-dessous, j'ai à la fois des lignes horizontales et des lignes verticales sur le même feuillet. Je ne sais pas comment traiter cette difficulté. Je pense que si je réalise les lignes verticales manuellement, elles ne seront pas forcément transcrites par la suite. Il faudra que je transcrive moi-même. Si jamais vous rencontrez ce problème et/ou si vous avez une solution, n'hésitez pas à m'en faire part. 

![Capture d’écran de 2021-12-23 20-14-25](https://user-images.githubusercontent.com/92677204/147287882-4a600859-5e83-4886-8799-ee889a8f481a.png)

Je vous remercie par avance !

**Comment by FannyLbr** [comment]
Bonjour les filles, 
Je reviens sur mon message précédent, car j'ai re essayé la segmentation des lignes verticales et cela a fonctionné. Je vous explique ma méthode, peut-être que cela vous sera utile pour vos lettres respectives. 

La segmentation automatique spécifique aux lignes verticales n'a pas fonctionné pour mes cas (cela est sûrement dû à la qualité des manuscrits). J'ai donc fait le choix de faire la segmentation manuellement. 
- Pour ce qui concerne les images avec les adresses/destinataires, j'ai créé une seule zone et j'ai défini chaque ligne, tout en faisant bien attention à la numérotation de ces dernières. 
- Pour ce qui concerne l'autre cas (l'image avec les lignes horizontales et verticales), j'ai fait le choix de créer une zone propre aux lignes horizontales, puis une zone à chaque fois qu'un groupement de lignes verticales était présent. J'ai appliqué la segmentation automatique pour les lignes horizontales puis j'ai tracé manuellement la segmentation verticale, tout en faisant là aussi attention à la numérotation des lignes.

Après ce travail sur la segmentation, j'ai lancé la transcription automatique et cela a fonctionné. Je pense que la première fois que j'avais tenté, eScriptorium a dû avoir des bugs, car ma démarche était la même. J'ai essayé d'être encore plus précise pour le travail de segmentation, peut-être que cela a joué aussi. 

Voilà, en espérant que cela vous soit utile !

**Comment by SjdkC** [comment]
Bonjour Fanny !

Désolée pour la réponse tardive !
Merci beaucoup pour ces explications ! Concernant la numérotation des lignes, comment as-tu procédé ? As-tu numéroté les lignes verticales à la suite des lignes horizontales (c'est ce que je pensais faire), ou as-tu adopté un autre système ?

Je te remercie par avance pour ta réponse !

**Comment by FannyLbr** [comment]
Pas de souci ! 
Pour ce qui concerne la numérotation des lignes horizontales et verticales, j'ai fait le choix de les numéroter en fonction de la logique de lecture de la lettre, autrement dit en fonction de la signification/ du sens de la lettre. Pour ma part, les lignes verticales correspondaient à la fin logique de ma lettre (peut-être que cela est différent pour toi ?). Voici ci-dessous la numérotation effectuée sur eScriptorium : 
![Capture d’écran de 2021-12-28 18-52-35](https://user-images.githubusercontent.com/92677204/147593523-7203cf5d-c335-4534-a30e-d43aa6a944e2.png)

Cela me paraissait assez logique de faire comme cela. Êtes-vous d'accord avec cette décision ?

**Comment by SjdkC** [comment]
Je te remercie pour cet exemple.
Cette solution me semble pertinente, je pense que nous pouvons l'adopter !

**Comment by Lienceard** [comment]
Bonjour Fanny,

Je suis désolée de n'avoir pas pu te répondre plus tôt.
Je te remercie beaucoup pour ton aide. Je me posais les mêmes questions étant donné que je rencontre également des lignes verticales à transcrire. Tes explications et l'exemple me paraissent assez clairs.
Oui, le choix de la numérotation des lignes dans ton exemple me semble le bon. 
Je rejoins Cécile. Nous pouvons adopter cette méthode.

**Comment by FannyLbr** [comment]
Super, on adopte cela alors !

**Comment by SjdkC** [comment]
Bonjour à toutes,

Au moment de segmenter mes pages, ma compréhension a été qu'il n'est pas possible de numéroter manuellement les lignes. J'ai donc utilisé la numérotation automatique (en faisant CTRL+A pour sélectionner les lignes, puis en utilisant les boutons "unlink" puis "link", afin de bien obtenir une numérotation qui tient compte des régions).

Cependant, à la relecture, ce problème m'a paru plus apparent. Au sein d'une zone de texte vertical, j'obtiens par exemple :

![image](https://user-images.githubusercontent.com/92724884/147824931-4ace3a92-1266-41bd-8eca-7a81774a693b.png)

Ici, la numérotation commence bien à 30 (la région principale s'arrête à la ligne 29), mais une numérotation idéale, qui respecte l'ordre de lecture, aurait plutôt été 33-32-31-30.

C'est un problème isolé, et il me semble qu'il est minoré par le lien entre le texte et l'image qui sera au final restitué par le fichier XML ALTO, mais je voulais quand même voir si vous avez aussi rencontré (et peut-être réglé !) ce problème. Dans tous les cas, je vous remercie par avance pour votre retour !

**Comment by FannyLbr** [comment]
Bonjour Cécile, 

J'ai eu aussi ce souci pour la numérotation de mes lignes. Voici ce que j'ai fait pour résoudre l'ordre : 
- J'ai tout d'abord cliqué sur le bouton du milieu comme ci-dessous (il devient vert une fois que tu as cliqué dessus) : 

![Capture d’écran de 2021-12-31 14-36-10](https://user-images.githubusercontent.com/92677204/147826044-955d5878-68e6-485f-95cd-f3371b8aaa1b.png)

![Capture d’écran de 2021-12-31 14-36-19](https://user-images.githubusercontent.com/92677204/147826048-3b215590-f121-4f81-809b-70469b8f9a73.png)

- Ensuite, j'ai sélectionné manuellement la ligne que je voulais bouger et je l'ai déplacée là où je le souhaitais. Il faut que tu cliques sur le chiffre de la ligne et que tu le glisses à l'endroit que tu veux. 
![Capture d’écran de 2021-12-31 14-36-44](https://user-images.githubusercontent.com/92677204/147826183-85684025-5804-46ef-9d7c-3133b6df70af.png)
 
Normalement, après cela, la numérotation sur ton image change, et correspond à ce que tu souhaites. J'espère que cela t'aidera !

**Comment by Lienceard** [comment]
Bonjour Cécile,

Normalement il y a un moyen de le faire automatique d'après Maxime et c'est je pense ce que tu as fait. Mais j'avoue je n'ai pas trop compris comment il l'a fait. Fanny a répondu avant moi, mais j'avais également cherché et rapidement testé sa méthode. Elle fonctionne mais c'est un peu long surtout quand on a une cinquantaine de lignes auxquelles il faut changer l'ordre de la numérotation.

**Comment by Lienceard** [comment]
je vous mets ici les conseils de Maxime....
C'est l'étape 1 que je ne comprends pas trop..
Etapes :
1- Sélectionner les zones et les ciseaux afin de découper les zones en fonction des colonnes, titres ect. PS : @ValentinDeCraene on est pas au pixel près. 💯
2- Desélectionner les zones et les ciseaux, sélectionner les lignes, puis faire ctrl + a
3- Appuyer sur "Unlink" (la touche U) puis appuyer "Link" (la touche Y)

**Comment by SjdkC** [comment]
Je te remercie vivement, Fanny : j'ai suivi tes conseils, et tout a très bien fonctionné ! :)

Lien, ce que tu décris correspond justement à la méthode que j'avais utilisée initialement (c'est ce que j'avais essayé d'expliquer dans mon message d'hier, mais ce n'était peut-être pas très clair). Merci malgré tout !
