### ISSUE TITLE
Problèmes git et github

### ISSUE THREAD

**Issue by FannyLbr** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#7]
Bonjour les filles, 

Je crée cette issue portant sur les problèmes liés à git et github. 

Je me suis aperçue, après quelques manipulations et en consultant l'historique, que je m'étais trompée plusieurs fois dans mes commits. Cela concerne 2 fichiers : "choix_exports_et_conventions_de_nommage.md" et "tableau_de_gestion.md". Pour rappel, ces deux fichiers ont été créés directement sur github, c'est pourquoi, pour les modifier, j'ai réalisé des commits directement sur github sans passer par git (edit this file -> modification sur le document -> puis commit changes).

Après avoir vu l'historique, je me suis rendu compte qu'au lieu de mettre un message de commit dans "commit changes", j'avais soit mis le nom du fichier, soit je n'avais rien mis. Puis lorsque j'ai compris mon erreur, j'ai créé un nouveau commit avec un message, mais je ne suis pas satisfaite de celui-ci. Cela apparaît dans l'historique malheureusement... 

J'ai cherché dans la documentation de github une solution pour essayer de modifier le nom de ces commits, mais je n'ai pour l'instant rien trouvé. Modifier/ corriger un commit avec git, je connais les méthodes, mais lorsque ce sont des commits directement réalisés sur github, je ne vois pas comment faire. 

Si jamais vous aviez une solution à m'apporter, n'hésitez pas à m'en faire part. De toute façon, les fautes ne sont pas extrêmement graves, et je ne reproduirai plus ces erreurs. Mais je pense que cela pourrait être intéressant et utile de savoir corriger ces erreurs sur github aussi. Pour info (et pour que vous évitiez de faire les mêmes erreurs que moi), je vous mets ci-joint le lien vers la documentation github concernant la gestion de fichiers sur github : https://docs.github.com/en/repositories/working-with-files/managing-files/creating-new-files.

Je vous remercie par avance pour votre aide !

**Comment by Lienceard** [comment]
Bonjour Fanny, 

j'ai également cherché de mon côté. J'ai trouvé quelque chose d'intéressant sur ce site dont je te mets le lien ci-dessous. Toutefois, je préfère que tu le fasses car je ne sais pas exactement ce que tu souhaites garder et supprimer. Il faudrait peut-être faire des essais dans un autre dépôt Git Hub pour s'entraîner car on peut perdre notre travail. 
Enfin, les "erreurs" que tu penses avoir faites ne me paraissent pas trop importantes pour que tu sois obligée de supprimer ou bien de modifier un commit sur Git Hub. Mais cela peut être toujours utile.

https://www.it-swarm-fr.com/fr/git/comment-puis-je-supprimer-un-commit-sur-github/958195671/

Bonne journée.

**Comment by FannyLbr** [comment]
Merci beaucoup Lien pour ce lien. Effectivement, je suis tombée sur plusieurs explications comme celle-ci, mais il me semble que cela ne soit pas exactement mon cas. Dans cette explication, l'erreur est sur un commit "pushé" vers github. Or moi, je n'ai rien pushé du tout, j'ai fait un commit directement sur github. Il est peut-être possible, en effet, de récupérer cela en local et de le modifier par git. Mais je trouve cela compliqué et étonnant de ne pas avoir de solution directement sur github. 

Je vais quand même essayer de m'entraîner sur un autre dépôt et d'appliquer les commandes évoquées dans ton lien.

**Comment by FannyLbr** [comment]
J'ai essayé sur un autre dépôt les commandes suivantes afin d'au moins pouvoir modifier le message de mon dernier commit : 
git pull origin main (j'ai récupéré la branche main pour être à jour)
git commit --amend -m "Nouveau message" (création du nouveau message du commit)
git push --force (envoyer cela sur github)
Cela a très bien fonctionné. J'ai décidé de l'appliquer sur notre dépôt à nous (branche main), mais impossible de pusher. J'ai donc annulé cette manipulation. Je laisse cela en suspens pour le moment.

**Comment by SjdkC** [comment]
Je suis d'accord avec Lien : il me semble que ce ne sont pas des erreurs majeures. Je ne pense pas que l'on doive se formaliser de cet oubli de nom de commit, d'autant que cette erreur est maintenant documentée ici.

En revanche, je pense que nous pourrons parler de tout ceci dans notre rapport final (afin de dire, par exemple, que la création ou la modification de documents est certes facile et pratique dans Github, mais qu'elle a aussi des défauts par rapport à l'utilisation du terminal...).

**Comment by FannyLbr** [comment]
Oui, vous avez raison, cela n'est pas le plus important. Je ne pense pas me lancer dans d'autres essais pour réparer ces erreurs puisqu'elles sont documentées ici. L'essentiel, c'est de ne pas reproduire ces erreurs afin d'avoir un historique le plus clair possible.

Oui, tout à fait d'accord !

**Comment by Lienceard** [comment]
Je suis d'accord avec Cécile,
Je suis désolée Fanny, mais je ne vois pas trop pourquoi cela n'a pas fonctionné ta manipulation. 
Je suis d'accord qu'il faudrait rajouter ces remarques dans le rapport. 
Les commandes de bases avec Git sont relativement faciles à prendre en main. Toutefois, quand il s'agit de faire des manipulations un peu plus complexe notamment revenir sur une manipulation antérieure en raison d'une erreur comme c'est le cas ici c'est vraiment pas évident...

**Comment by Lienceard** [comment]
Bonjour à toutes,

Prochainement nous allons devoir réaliser un certain nombre de pull requests notamment pour les relectures des transcriptions.
Je me sens pas tellement à l'aise avec cette fonctionnalité. J'aurais recevoir des explications sur le procédé à adopter. 

Je vous remercie d'avance pour vos renseignements apportés.

**Comment by SjdkC** [comment]
Bonjour Lien,

Concernant les PR, dans le cas des relectures de transcriptions, je propose de passer directement par l'interface de Github, avec la procédure suivante :

Nos transcriptions sont au format texte ; nous pouvons donc les modifier directement dans Github, puis proposer ces corrections en faisant une pull request. 
Si je veux proposer des corrections pour la Lettre X, je les inscrirai ainsi dans le document, puis je proposerai une PR :
![image](https://user-images.githubusercontent.com/92724884/147854359-b983de80-1f75-493f-8cfa-18434a87c3f7.png)
Une fois ceci validé, j'arriverai sur une autre page qui permettra d'indiquer vers quelle branche on aimerait merge (si notre PR est approuvée), et d'éventuellement demander à des personnes en particulier de donner son avis sur la PR.

Dans tous les cas, si la PR est approuvée, il ne faudra pas oublier de reporter les corrections adoptées dans eScriptorium (afin d'obtenir un export XML ALTO complet et bien corrigé à la fin).

**Comment by FannyLbr** [comment]
Je ne suis pas à l'aise non plus, comme Lien, sur les PR, mais Cécile, ton message est très clair et devrait m'aider également, alors merci !

**Comment by Lienceard** [comment]
Je te remercie beaucoup Cécile pour tes explications. Cela me paraît beaucoup plus clair maintenant.

**Comment by Lienceard** [comment]
Bonjour,

Suite à nos récentes discussions, je vous transmets dans cette issue un lien vers une vidéo qui explique le fonctionnement des pull requests depuis GitHub.
Je trouve que c'est très bien expliqué. 

https://www.youtube.com/watch?v=YRAm14PNWg8

**Comment by FannyLbr** [comment]
Merci beaucoup Lien pour cette vidéo. Cela devrait nous aider aussi.

**Comment by SjdkC** [comment]
Suite à nos échanges de tout à l'heure, je précise que, contrairement à ce que j'ai indiqué dans ma capture d'écran un peu plus haut, il est préférable de justifier ses propositions de corrections dans le message de la PR (donc sur la page qui s'affiche lorsque l'on valide le formulaire), plutôt que dans le champs de description du "commit change".

**Comment by FannyLbr** [comment]
Bien noté, merci Cécile !
