### ISSUE TITLE
Remplir le README pour une meilleure documentation

### ISSUE THREAD

**Issue by SjdkC** [Lienceard/TNAH-2021-Projet-Correspondance-Berlioz#9]
Bonjour à toutes,

J'ouvre cette issue pour discuter du contenu du README, qui devrait servir de présentation au projet. En effet, puisque nous devons partir du principe que de nouveaux participants pourraient rejoindre le projet à tout moment, il me semble important de le remplir dès maintenant, sans attendre la fin du projet.

Je propose donc d'inscrire dans le README :

1. Un paragraphe de présentation du projet :

    - Contexte : rappeler que ce projet a été créé dans le cadre du module Git dispensé par Thibault Clérice pour le M2 TNAH de l'ENC.
    - Objectifs : rappel de la consigne du devoir.
    - Corpus : lien vers le recueil Gallica des lettres de Berlioz à sa soeur, et éventuellement rappel (sommaire) de celles que nous avons pour le moment retenues.
    - Projet : faire le lien avec les problématiques d'HTR, l'intérêt du corpus.
    
2. Une description de l'architecture du dépôt, avec un renvoi vers les fichiers organisationnels importants, notamment le tableau de bord et le fichier sur les conventions de nommage et les choix d'exports (et par la suite, vers celui qui concernera les normes de transcription).
4. Une liste des collaborateurs actuels, avec leurs rôles (même si nous partageons toutes les mêmes rôles, dans les faits) et éventuellement l'équivalence noms/pseudos Github.
5. Un point sur l'état du projet : dire que le projet est actuellement en cours.

Que pensez-vous de tout cela ? N'hésitez pas également à me dire si vous avez pensé à d'autres points importants à inclure.

Une fois que nous nous serons mises d'accord, je veux bien me charger de remplir le README si cela vous va.

**Comment by FannyLbr** [comment]
Bonsoir Cécile,

C'est une très bonne idée, et je suis d'accord avec toi, le README est un élément important que nous devrions compléter sans trop tarder. 

Les différents points que tu pointes me semblent très pertinents et utiles ! Pour l'instant, je ne vois rien d'autres à ajouter.

Si Lien est d'accord, je suis ok pour que tu le fasses. 
Si je pense à d'autres éléments d'ici là, je t'en ferai part ici. Et si jamais tu as besoin d'aide, n'hésite pas. 

Merci à toi !

**Comment by SjdkC** [comment]
Merci pour ta réponse Fanny !
J'attends le retour de Lien et le README pourra être rédigé !

**Comment by Lienceard** [comment]
Bonjour les filles, 

Finalement je préfère laisser à Cécile la rédaction du README car j'ai pris du retard sur mes transcriptions. 
Sinon, je valide le plan. Oui, il est important à présent de penser à rédiger le README pour documenter le projet. 
Par ailleurs, quand on le relira on pourrait  si besoin essayer de faire des pull requests. Ce serait l'occasion idéale pour s'entraîner avec cette autre fonctionnalité de Git Hub. 

Qu'en pensez-vous?

**Comment by SjdkC** [comment]
D'accord merci pour ton retour sur le plan ! Je vais m'y mettre :)

Pourquoi pas, oui, pour les pull requests, si des choses ne vous conviennent pas n'hésitez pas !

**Comment by Lienceard** [comment]
d'autant plus que le document sur lequel nous travaillons est sur la branche main et ce n'est pas une transcription donc c'est un peu plus rassurant pour tester les pull request...

**Comment by FannyLbr** [comment]
Ça me va aussi pour les PR ! On verra cela au moment de la relecture.

**Comment by SjdkC** [comment]
Le README est rempli, je clôture pour le moment !
